name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "cloud-mail"		#d1数据库名字
#~ database_id = "95178815-3ccb-46b0-8f31-d107cb8671bc"		#d1数据库id
database_id = "393ddd71-b3c9-44e5-b800-a5b1cfe6fe24"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
#~ id = "07bad49862734db382f98e68479c5f49"					#kv数据库id
id = "b2397f828f414a0b99762f70decf6f99"					#kv数据库id

[[r2_buckets]]
binding = "r2"			#r2对象存储绑定名默认不可修改
bucket_name = "cloud-mail"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
orm_log = false
#~ domain = ["chez.de5.net"]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
domain = ["maison.de5.net"]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@maison.de5.net"				#管理员的邮箱	示例: admin@example.com
jwt_secret = "fafdc3f7-8817-4156-be70-49f1e0b577ff"			#jwt令牌的密钥,随便填一串字符串

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
